sudo: required
services:
    - docker

before_install:
    - docker build -t darshanadsw/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true darshanadsw/docker-react npm run test -- --coverage